title: Yuzhe Yang's Homepage
page-top-title: Yuzhe Yang
top-section-bg-text: Control Science and Engineering
home-subtitle: Yuzhe Yang&ensp;|&ensp;杨宇哲
copyright-text: '&copy; Yuzhe Yang 2025-2025. All Rights Reserved.'
